name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: >
          Thank you for raising your first issue in this repository! 🎉  
          Please ensure you’ve included all necessary details to help us address your issue effectively.  
          We appreciate your contribution and look forward to collaborating with you! 🙏
        pr-message: >
          Thank you for your first pull request! 🎉  
          Please ensure your code adheres to our guidelines and includes relevant comments for clarity.  
          Your efforts make a difference, and we’re thrilled to have you on board! 🙏
